name: RobotSystem
version: '${version}'
main: yt.szczurek.robotsystem.RobotSystem
api-version: '1.20'
dependencies:
    bootstrap:
      MCKotlin-Paper:
        load: BEFORE
        required: true
        join-classpath: true
    server:
      AuthMe:
        load: BEFORE
        required: true
        join-classpath: true
authors: [Burzowy_Szczurek]
